### ISSUE TITLE
Link at startup more than one module 

### ISSUE THREAD

**Issue by iw0red** [n7tae/QnetGateway#10]
Hi everyone,
may I connect module A and module B at startup and to the same xrf? I have an icom repeater with voice modules A, B and C. 
Thanks in advance.
73 Marco IW0RED.

link = {
        link_at_start = "AXRF068B" # Link to a reflector at startup.
  
[....]

**Comment by n7tae** [comment]
Hi Marco,
Currently, the "link_at_start" only supports a single linking command (for a single channel). I am working on a different branch right now, so it will be a few weeks before I can get back to fix this. I will leave this open as a reminder to me to fix this.

**Comment by iw0red** [comment]
Fine thanks! 👍

**Comment by iw0red** [comment]
I connected manually module A and B after that I can see a lot messages like these:

New g2 port from 192.168.2.120 is now 18997, it was 30001
New g2 port from 192.168.2.120 is now 30001, it was 18997
New g2 port from 192.168.2.120 is now 18997, it was 30001
New g2 port from 192.168.2.120 is now 30001, it was 18997
New g2 port from 192.168.2.120 is now 18997, it was 30001
New g2 port from 192.168.2.120 is now 30001, it was 18997
New g2 port from 192.168.2.120 is now 18997, it was 30001
New g2 port from 192.168.2.120 is now 30001, it was 18997
New g2 port from 192.168.2.120 is now 18997, it was 30001
New g2 port from 192.168.2.120 is now 30001, it was 18997
New g2 port from 192.168.2.120 is now 18997, it was 30001
New g2 port from 192.168.2.120 is now 30001, it was 18997
[...]
73 Marco IW0RED.

**Comment by n7tae** [comment]
Yes, that's normal. That's the QnetGateway tracking the ports of each incoming connection. This it to help reconnect to clients that are operating from a smart-phone tethered hot-spot. Most cell providers are constantly remapping port numbers.

**Comment by n7tae** [comment]
Both QnetGateway and the new QnetIcomGateway support "Link at startup" on each configured module. Of course, each module can be linked to a different repeater/reflector.
