### ISSUE TITLE
Unlink timeout

### ISSUE THREAD

**Issue by iw0red** [n7tae/QnetGateway#8]
Hi,
isn't  there any reconnection after a random disconnection as I can see?
[....]
Added 4417 gateways
g2_link QnetLink-6.0.0 initialized...entering processing loop
xrf=3, dcs=4, ref=5, rptr=6, MAX+1=7
sleep for 15 before link at startup
sending link request from mod A to link with: [XRF068  ] mod B [92.222.145.202]
Connected from: [XRF068  ] B
sending File:[/root/QnetGateway/announce/linked.dat], mod:[A], RADIO_ID=[LINKED XRF068 B     ]
sending ACK+text, mod:[A], RADIO_ID=[LINKED TO XRF068  B ]
Unlinked from [XRF068  ] mod B, TIMEOUT...
sending File:[/root/QnetGateway/announce/unlinked.dat], mod:[A], RADIO_ID=[UNLINKED TIMEOUT    ]

73 Marco IW0RED.

**Comment by n7tae** [comment]
Yes. If you are disconnected by a reflector or repeater, you have to manually re-link.

**Comment by iw0red** [comment]
Did you plan to add this features?
73 Marco IW0RED.

**Comment by n7tae** [comment]
Thanks for your question, Marco. I'll look into it the next time I am working on QnetLink. Until then, I will leave this item opened.

**Comment by iw0red** [comment]
Thanks for the answer.
73 Marco IW0RED

**Comment by n7tae** [comment]
Sorry for taking so long to fix this, but it is done now! Please see the comments about how it works in the OPERATING file in section on linking.
