### ISSUE TITLE
icom repeater issue

### ISSUE THREAD

**Issue by iw0red** [n7tae/QnetGateway#9]
[qn_cfg.txt](https://github.com/n7tae/QnetGateway/files/2660589/qn_cfg.txt)

Hi everyone, I'm trying to setup my icom repeater but there is something wrong. 
I use armbian orange pi zero: 
- Linux orangepizero 4.14.84-sunxi #3 SMP Sat Dec 1 07:18:41 CET 2018 armv7l GNU/Linux;
- eth0: inet 192.168.2.147  netmask 255.255.255.0  broadcast 192.168.2.255
- eth0:0: inet 172.16.0.254  netmask 255.255.255.0  broadcast 172.16.0.255
 and icom id-rp2c (172.16.0.1/24) connected to id-rp400v (430)  and idrp2v (1200) 
Attached my qn.cfg.
Thanks,
73 Marco IW0RED.

**Comment by n7tae** [comment]
Sorry Marco, but QnetGateway doesn't support the 23cm data module. If you are still interested in getting your 70cm module up on QnetGateway, I suggest you post questions on the QnetGateway.groups.io site. There will be more help available there.

In your config file, you have a C module defined with zero frequency. You have also places quotes around numeric values. This is unnecessary.

Remember that **if** a config parameter's default value is okay with your setup, you don't need to uncomment it. In fact it's best to remove it altogether so you config file is left only with definitions that override the default value. For example, the ircddb section will usually only define a login parameter.

**Comment by iw0red** [comment]
Fine thanks I'll try.
73 Marco IW0RED.
